/*
 * File: app/view/PlacesContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PlacesApp.view.PlacesContainer', {
    extend: 'Ext.Container',
    alias: 'widget.placescontainer',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'searchfield',
                label: 'Field'
            },
            {
                xtype: 'list',
                flex: 1,
                itemTpl: [
                    '<div class="title">',
                    '    {name}',
                    '</div>',
                    '<tpl if="rating">',
                    '    <div class="rating_holder">',
                    '        <tpl if=\'Math.floor(rating) &gt; 0\'>',
                    '        	<div class="rating"></div>',
                    '        </tpl>',
                    '        <tpl if=\'Math.floor(rating) &gt; 1\'>',
                    '        	<div class="rating"></div>',
                    '        </tpl>',
                    '        <tpl if=\'Math.floor(rating) &gt; 2\'>',
                    '        	<div class="rating"></div>',
                    '        </tpl>',
                    '        <tpl if=\'Math.floor(rating) &gt; 3\'>',
                    '        	<div class="rating"></div>',
                    '        </tpl>',
                    '        <tpl if=\'Math.floor(rating) &gt; 4\'>',
                    '        	<div class="rating"></div>',
                    '        </tpl>',
                    '    </div>',
                    '</tpl>'
                ],
                store: 'PlacesStore'
            }
        ]
    }

});